//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academy_info
    {
        public int ID_academy { get; set; }
        public string Name_academy { get; set; }
        public string phone_academy { get; set; }
        public string email_academy { get; set; }
        public string Adress_academy { get; set; }
        public bool Status_academy { get; set; }
    }
}
