//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee_Group = new HashSet<Employee_Group>();
        }
    
        public int ID_emp { get; set; }
        public string Name_emp { get; set; }
        public string Surname_emp { get; set; }
        public string Email_emp { get; set; }
        public string Phone_emp { get; set; }
        public string Speciality_emp { get; set; }
        public int PositionID { get; set; }
        public System.DateTime StartTime { get; set; }
        public decimal Salary { get; set; }
        public bool Status_emp { get; set; }
    
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Group> Employee_Group { get; set; }
    }
}
