//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Group
    {
        public int ID_task_gr { get; set; }
        public int GroupID { get; set; }
        public int TaskID { get; set; }
        public bool Status_task_gr { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Task Task { get; set; }
    }
}
